server:
  port: 8080
  servlet:
    context-path: /myapp

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: my-spring-boot-app

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

factory:
  url: http://localhost:7455/purchase-order

logging:
  level:
    root: info
    com.example.myapp: debug
#    org.springframework.boot: DEBUG

management:
  #  datadog:
  #    metrics:
  #      export:
  #        api-key: ${DATADOG_API_KEY:default-api-key-here}
  #        application-key: ${DATADOG_APPLICATION_KEY:default-application-key-here}
  #        step: 10s
  #        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      logging:
        enabled: true